// Generated by CoffeeScript 1.8.0
(function() {
  define(function() {
    return {
      tabChange: function() {
        return console.log('active tab  changed...');
      },
      doWaiting: function() {
        var deferredView, views, _feature;
        this.feature.activeTab = 'waiting';
        if (!this.feature.views['process:body-waiting']) {
          views = [];
          views.push({
            name: 'process:toolbar-waiting',
            region: 'toolbar-waiting'
          });
          views.push({
            name: 'process:body-waiting',
            region: 'body-waiting'
          });
          if (!this.feature.views['process-form:show']) {
            views.push('process-form:show');
          }
          if (!this.feature.views['process-form:complete']) {
            views.push('process-form:complete');
          }
          deferredView = this.feature.initViews(views);
          _feature = this.feature;
          deferredView.done(function() {
            _feature.layout['toolbar_waiting'].show(_feature.views['process:toolbar-waiting']);
            return _feature.layout['body_waiting'].show(_feature.views['process:body-waiting']);
          });
        }
        $('.c-doing').hide();
        $('.c-done').hide();
        $('.c-none').hide();
        return $('.c-waiting').show();
      },
      doDoing: function() {
        var deferredView, views, _feature;
        this.feature.activeTab = 'doing';
        if (!this.feature.views['process:body-doing']) {
          views = [];
          views.push({
            name: 'process:toolbar-doing',
            region: 'toolbar-doing'
          });
          views.push({
            name: 'process:body-doing',
            region: 'body-doing'
          });
          if (!this.feature.views['process-form:show']) {
            views.push('process-form:show');
          }
          if (!this.feature.views['process-form:complete']) {
            views.push('process-form:complete');
          }
          if (!this.feature.views['process-form:reject']) {
            views.push('process-form:reject');
          }
          deferredView = this.feature.initViews(views);
          _feature = this.feature;
          deferredView.done(function() {
            _feature.layout['toolbar_doing'].show(_feature.views['process:toolbar-doing']);
            return _feature.layout['body_doing'].show(_feature.views['process:body-doing']);
          });
        }
        $('.c-waiting').hide();
        $('.c-done').hide();
        $('.c-none').hide();
        return $('.c-doing').show();
      },
      doDone: function() {
        var deferredView, views, _feature;
        this.feature.activeTab = 'done';
        if (!this.feature.views['process:body-done']) {
          views = [];
          views.push({
            name: 'process:toolbar-done',
            region: 'toolbar-done'
          });
          views.push({
            name: 'process:body-done',
            region: 'body-done'
          });
          if (!this.feature.views['process-form:show']) {
            views.push('process-form:show');
          }
          deferredView = this.feature.initViews(views);
          _feature = this.feature;
          deferredView.done(function() {
            _feature.layout['toolbar_done'].show(_feature.views['process:toolbar-done']);
            return _feature.layout['body_done'].show(_feature.views['process:body-done']);
          });
        }
        $('.c-waiting').hide();
        $('.c-doing').hide();
        $('.c-none').hide();
        return $('.c-done').show();
      },
      doAll: function() {
        var deferredView, views, _feature;
        this.feature.activeTab = 'none';
        if (!this.feature.views['process:body-none']) {
          views = [];
          views.push({
            name: 'process:toolbar-none',
            region: 'toolbar-none'
          });
          views.push({
            name: 'process:body-none',
            region: 'body-none'
          });
          views.push('process-form:add');
          views.push('process-form:edit');
          views.push('process-form:show');
          deferredView = this.feature.initViews(views);
          _feature = this.feature;
          deferredView.done(function() {
            _feature.layout['toolbar_none'].show(_feature.views['process:toolbar-none']);
            return _feature.layout['body_none'].show(_feature.views['process:body-none']);
          });
        }
        $('.c-waiting').hide();
        $('.c-doing').hide();
        $('.c-done').hide();
        return $('.c-none').show();
      },
      doWrite: function() {}
    };
  });

}).call(this);
