// Generated by CoffeeScript 1.8.0
(function() {
  define(['text!cdeio/layouts/templates/grid.html'], function() {
    return {
      regions: {
        toolbar: 'toolbar',
        body: 'body'
      },
      avoidLoadingHandlers: false,
      events: {
        'click ok': 'doFilter',
        'click reset': 'doReset'
      },
      components: [
        function() {
          var options, _ref, _ref1;
          options = ((_ref = this.feature.options.inlineGrid) != null ? _ref.picker : void 0) || ((_ref1 = this.feature.startupOptions.inlineGrid) != null ? _ref1.picker : void 0);
          if (!options) {
            return false;
          }
          return _.extend({}, options, {
            selector: 'picker',
            type: 'grid-picker'
          });
        }
      ]
    };
  });

}).call(this);
