// Generated by CoffeeScript 1.8.0
(function() {
  define(['text!cdeio/layouts/templates/one-region.html'], function() {
    return {
      regions: {
        main: "one-region"
      }
    };
  });

}).call(this);
