// Generated by CoffeeScript 1.8.0
(function() {
  define(['text!cdeio/layouts/templates/process.html'], function() {
    return {
      regions: {
        tabs: 'tabs',
        toolbar_waiting: 'toolbar-waiting',
        toolbar_doing: 'toolbar-doing',
        toolbar_done: 'toolbar-done',
        toolbar_none: 'toolbar-none',
        body_waiting: 'body-waiting',
        body_doing: 'body-doing',
        body_done: 'body-done',
        body_none: 'body-none',
        filter: 'filter'
      },
      avoidLoadingHandlers: false,
      events: {
        'click p-waiting': 'doWaiting',
        'click p-doing': 'doDoing',
        'click p-done': 'doDone',
        'click p-all': 'doAll',
        'click p-write': 'doWrite'
      },
      components: [
        function() {
          var options, _ref, _ref1;
          options = ((_ref = this.feature.options.inlineGrid) != null ? _ref.picker : void 0) || ((_ref1 = this.feature.startupOptions.inlineGrid) != null ? _ref1.picker : void 0);
          if (!options) {
            return false;
          }
          return _.extend({}, options, {
            selector: 'picker',
            type: 'grid-picker'
          });
        }
      ],
      extend: {
        render: function() {
          return console.log(this, 111);
        }
      }
    };
  });

}).call(this);
