// Generated by CoffeeScript 1.8.0
(function() {
  define({
    avoidLoadingHandlers: true,
    extend: {
      serializeData: function(su) {
        var data, p, view, _params;
        data = su.apply(this);
        data.report = this.feature.startupOptions.report;
        data.load = true;
        _params = '';
        if (this.feature.startupOptions.params) {
          for (p in this.feature.startupOptions.params) {
            _params += "&" + p + "=" + this.feature.startupOptions.params[p];
          }
          data.params = _params;
        } else if (this.feature.startupOptions.paramsView) {
          if (this.feature.startupOptions.paramsView) {
            view = this.feature.startupOptions.paramsView;
            app.showDialog({
              view: view,
              title: '参数设置',
              buttons: [
                {
                  label: '确定',
                  status: 'btn-primary',
                  fn: (function(_this) {
                    return function() {
                      if (!view.isValid()) {
                        return false;
                      }
                      return app.startFeature('cdeio:report', {
                        report: _this.feature.startupOptions.report,
                        params: view.getFormData(),
                        paramsView: view,
                        callback: _this.feature.startupOptions.callback
                      }).done(function(feature) {
                        var callback;
                        callback = feature.startupOptions.callback;
                        if ($.isFunction(callback)) {
                          return callback.call(feature, feature);
                        }
                      });
                    };
                  })(this)
                }
              ]
            });
          }
          data.load = false;
        }
        return data;
      }
    }
  });

}).call(this);
