// Generated by CoffeeScript 1.8.0
(function() {
  define({
    events: {
      'click birt-boolbar-*': 'birt_toolbar_click',
      'click birt-parameter': 'birt_parameter_click'
    }
  });

}).call(this);
