// Generated by CoffeeScript 1.8.0
(function() {
  define({
    routes: {
      "start/*path": "hello"
    },
    hello: function(path) {
      return this.module.getApplication().startFeature(path);
    }
  });

}).call(this);
