// Generated by CoffeeScript 1.8.0
(function() {
  define({
    resizeToFit: function($grid, $parent) {
      var $bdiv, $header, $pager;
      if ($parent == null) {
        $parent = $grid.closest('.ui-jqgrid').parent();
      }
      $bdiv = $grid.parents('.ui-jqgrid-bdiv');
      $header = $bdiv.prev();
      $pager = $bdiv.parent().siblings().last();
      $grid.jqGrid('setGridHeight', $parent.height() - $header.height() - $pager.height() - 2);
      return $grid.jqGrid('setGridWidth', $parent.width() - 2);
    },
    onLayoutResize: function(x, ui) {
      var $ui, me;
      me = this;
      $ui = ui.jquery ? ui : $(ui.panel);
      return $ui.filter(':visible').find('.c-jqgrid-fit:visible').each(function() {
        var $grid;
        $grid = $(this);
        return me.resizeToFit($grid, $ui);
      });
    }
  });

}).call(this);
