// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery'], function($) {
    return {
      toggleSubMenu: function(e) {
        var el, t, ul;
        t = $(e.target);
        el = this.feature.layout.$el;
        ul = void 0;
        if (!t.is('a')) {
          t = t.parents('a');
        }
        ul = t.next();
        if (ul.is(':visible')) {
          return this.feature._closeSubMenu(ul, {
            enableAnimation: true
          });
        } else {
          return this.feature._openSubMenu(ul, {
            enableAnimation: true
          });
        }
      }
    };
  });

}).call(this);
