// Generated by CoffeeScript 1.8.0
(function() {
  define(['underscore', 'cdeio/cdeio', 'cdeio/vendors/jquery/jquery.easy-pie-chart.min'], function(_, cdeio) {
    return cdeio.registerComponentHandler('easy-pie', (function() {}), function(el, options, view) {
      var $box, barColor, oldie, opt, size, trackColor;
      $box = el.closest('.infobox');
      barColor = el.data('color') || (!$box.hasClass('infobox-dark') ? $box.css('color') : 'rgba(255,255,255,0.95)');
      trackColor = barColor === 'rgba(255,255,255,0.95)' ? 'rgba(255,255,255,0.25)' : '#E2E2E2';
      size = parseInt(el.data('size')) || 50;
      oldie = $.browser.msie && $.browser.version < 9;
      opt = _.extend({
        barColor: barColor,
        trackColor: trackColor,
        scaleColor: false,
        lineCap: 'butt',
        lineWidth: parseInt(size / 10),
        animate: oldie ? false : 1000,
        size: size
      }, options);
      el.css('color', barColor);
      return el.easyPieChart(opt);
    });
  });

}).call(this);
