// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery', 'cdeio/cdeio', 'cdeio/vendors/jquery/layout/jquery.layout'], function($, cdeio) {
    cdeio.registerComponentHandler('layout', (function() {}), function(el, options, view) {
      var layout, opts;
      opts = _.extend({
        view: view
      }, options);
      layout = el.layout(opts);
      layout.dispose = function() {
        return this.destroy();
      };
      return layout;
    });
    return $.layout.callbacks = {
      resizeLayout: function(container) {
        return container.filter(':visible').find('.ui-layout-container:visible').andSelf().each(function() {
          var layout;
          layout = $(this).data('layout');
          if (layout) {
            layout.options.resizeWithWindow = false;
            return layout.resizeAll();
          }
        });
      }
    };
  });

}).call(this);
