// Generated by CoffeeScript 1.8.0
(function() {
  define(['underscore', 'cdeio/cdeio', 'cdeio/vendors/jquery/jquery.maskedinput'], function(_, cdeio) {
    return cdeio.registerComponentHandler('mask', (function() {}), function(el, options, view) {
      var pattern;
      pattern = options.pattern || '';
      return el.mask(pattern, options);
    });
  });

}).call(this);
