// Generated by CoffeeScript 1.8.0
(function() {
  define(['underscore', 'cdeio/cdeio', 'cdeio/vendors/jquery/flot/jquery.flot.min', 'cdeio/vendors/jquery/flot/jquery.flot.pie.min', 'cdeio/vendors/jquery/flot/jquery.flot.resize.min'], function(_, cdeio) {
    return cdeio.registerComponentHandler('plot', (function() {}), function(el, options, view) {
      return $.plot(el, options.data, options);
    });
  });

}).call(this);
