// Generated by CoffeeScript 1.8.0
(function() {
  define(['underscore', 'jquery', 'cdeio/cdeio', 'cdeio/core/config', 'cdeio/vendors/jquery/select2/select2', 'cdeio/vendors/jquery/select2/select2_locale_zh-CN'], function(_, $, cdeio, config) {
    return cdeio.registerComponentHandler('select', (function() {}), function(el, opt, view) {
      var id, options, selector;
      if (opt.readOnly === true) {
        return {
          loadData: function(data) {
            return _(opt.data).each(function(item) {
              if (String(item.id) === String(data[opt.fieldName])) {
                return el.html(item.text);
              }
            });
          }
        };
      }
      options = _.extend({
        minimumResultsForSearch: config.minimumResultsForSearch
      }, opt);
      options.width = '100%';
      selector = el.select2(options);
      id = el.attr('id').split('-');
      id.shift();
      id = id.join('-');
      if (options.change && view.feature.options.scaffold.handlers[options.change]) {
        selector.on('change', function() {
          return view.feature.options.scaffold.handlers[options.change](view, selector);
        });
      }
      selector.dispose = function() {
        return this.select2('destroy');
      };
      return selector;
    });
  });

}).call(this);
