// Generated by CoffeeScript 1.8.0
(function() {
  define(['underscore', 'cdeio/cdeio', 'cdeio/vendors/jquery/jquery.sparkline.min'], function(_, cdeio) {
    return cdeio.registerComponentHandler('sparkline', (function() {}), function(el, options, view) {
      var $box, barColor, data, opt;
      $box = el.closest('.infobox');
      barColor = !$box.hasClass('infobox-dark') ? $box.css('color') : '#FFF';
      opt = _.extend({
        tagValuesAttribute: 'data-values',
        type: 'bar',
        barColor: barColor,
        chartRangeMin: el.data('min') || 0
      }, options);
      data = opt.data || 'html';
      return el.sparkline(data, opt);
    });
  });

}).call(this);
