// Generated by CoffeeScript 1.8.0
(function() {
  define(['jquery', 'underscore', 'cdeio/cdeio', 'cdeio/vendors/jquery/ui/tabs'], function($, _, cdeio) {
    return cdeio.registerComponentHandler('tabs', (function() {}), function(el, options, view) {
      var tabs;
      tabs = el.tabs(options);
      tabs.dispose = function() {
        return this.tabs('destroy');
      };
      return tabs;
    });
  });

}).call(this);
