// Generated by CoffeeScript 1.8.0
(function() {
  define(['config', 'underscore'], function(projectConfig, _) {
    var config;
    config = {
      applicationName: 'app',
      templateSuffix: '.html',
      featureContainer: 'body',
      modelDefinitionPath: 'definition',
      routerFileName: 'routers',
      scriptRoot: '/scripts',
      appRoot: 'app',
      helperPath: 'invoke/helper',
      cdeioFeaturesPath: 'cdeio/features',
      urlPrefix: 'invoke/scaffold/',
      minimumResultsForSearch: 10,
      featureFileName: 'feature',
      whitelist: [],
      folders: {
        layout: 'layouts',
        view: 'views',
        model: 'models',
        collection: 'collections',
        handler: 'handlers',
        template: 'templates'
      },
      getPath: function(feature, type, path) {
        var root;
        if (path.charAt(0) === '/') {
          root = true;
        }
        if (root === true) {
          path = path.substring(1);
        }
        return (root ? '/' : feature.baseName + '.feature/') + config.folders[type] + '/' + path;
      }
    };
    return _.extend(config, projectConfig);
  });

}).call(this);
