// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'cdeio/core/view', 'handlebars', 'cdeio/core/form/form-field', 'cdeio/core/form/form-group', 'cdeio/core/form/text-field', 'cdeio/core/form/date-picker-field', 'cdeio/core/form/date-time-picker-field', 'cdeio/core/form/textarea-field', 'cdeio/core/form/dropdown-field', 'cdeio/core/form/feature-field', 'cdeio/core/form/hidden-field', 'cdeio/core/form/file-picker-field', 'cdeio/core/form/mask-field', 'cdeio/core/form/number-range-field', 'cdeio/core/form/date-range-field', 'cdeio/core/form/inline-grid-field', 'cdeio/vendors/jquery/validation/messages_zh', 'cdeio/vendors/jquery/jquery.tooltipster.min'], function($, _, View, Handlebars, FormField, FormGroup) {

    /*
     * formName: 'add'
     * fieldGroups:
     *     group1: ['field1']
     *     group2: ['field2']
     * form:
     *     tabs: [
     *         {title: 'tab1', groups: ['group1', 'group2']}
     *     ]
     *     groups: ['group1', 'group2']
     */
    var FormView;
    FormView = (function(_super) {
      __extends(FormView, _super);

      function FormView(options) {
        var opt;
        opt = _.extend({}, options);
        this.initForm(opt.form, opt.fieldGroups, opt);
        _.extend(opt, {
          avoidLoadingModel: true
        });
        FormView.__super__.constructor.call(this, opt);
      }

      FormView.prototype.initForm = function(form, fieldGroups, options) {
        var components, events, group, groups, tab, unused, _i, _j, _k, _len, _len1, _len2, _ref;
        groups = form.groups;
        groups = _.isArray(groups) ? groups : [groups];
        this.groups = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = groups.length; _i < _len; _i++) {
            group = groups[_i];
            _results.push(this.createGroup(group, fieldGroups));
          }
          return _results;
        }).call(this);
        events = {};
        components = [];
        if (form.tabs) {
          unused = this.groups.slice(0);
          _ref = form.tabs;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            tab = _ref[_i];
            groups = tab.groups;
            groups = _.isArray(groups) ? groups : [groups];
            tab.id = _.uniqueId('tab');
            events['shown a-' + tab.id] = 'form-change-tab';
            for (_j = 0, _len1 = groups.length; _j < _len1; _j++) {
              group = groups[_j];
              unused = _.without(unused, this.findGroup(group));
              this.eachField(group, function(field) {
                var c, cs, es, _k, _len2, _ref1;
                if ((es = field.getEvents())) {
                  _.extend(events, es);
                }
                cs = field.getComponents();
                _ref1 = cs || [];
                for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
                  c = _ref1[_k];
                  c.delay = tab.id;
                }
                if (cs) {
                  return components = components.concat(cs);
                }
              });
            }
          }
          for (_k = 0, _len2 = unused.length; _k < _len2; _k++) {
            group = unused[_k];
            this.needExtraComponentRender = true;
            this.eachField(group.options.name, function(field) {
              var cs, es;
              if ((es = field.getEvents())) {
                _.extend(events, es);
              }
              if ((cs = field.getComponents())) {
                return components = components.concat(cs);
              }
            });
          }
          this.defaultComponentDelay = form.tabs[0].id;
          (this.eventHandlers || (this.eventHandlers = {}))['form-change-tab'] = (function(_this) {
            return function(e) {
              var deferred, id;
              id = $(e.target).attr('id');
              id = id.match(/a\-(\w+)/)[1];
              deferred = _this.renderComponents(id);
              if (deferred) {
                return deferred.done(function(components) {
                  return _this.setTabFormData(components);
                });
              }
            };
          })(this);
        } else {
          this.eachField(function(field) {
            var cs, es;
            if ((es = field.getEvents())) {
              _.extend(events, es);
            }
            if ((cs = field.getComponents())) {
              return components = components.concat(cs);
            }
          });
        }
        options.events = _.extend(options.events || {}, events);
        return options.components = (options.components || []).concat(components);
      };

      FormView.prototype.createGroup = function(group, fieldGroups) {
        var g;
        g = _.isString(group) ? {
          name: group
        } : group;
        return new FormGroup(this, g, fieldGroups[g.name]);
      };

      FormView.prototype.eachField = function(group, fn) {
        var field, fields, _i, _j, _len, _len1, _ref, _results, _results1;
        if (_.isFunction(group)) {
          fn = group;
          group = null;
        }
        if (!_.isFunction(fn)) {
          return;
        }
        if (group) {
          group = this.findGroup(group);
          fields = group.fields.concat(group.hiddenFields);
          _results = [];
          for (_i = 0, _len = fields.length; _i < _len; _i++) {
            field = fields[_i];
            _results.push(fn(field));
          }
          return _results;
        } else {
          _ref = this.groups;
          _results1 = [];
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            group = _ref[_j];
            fields = group.fields.concat(group.hiddenFields);
            _results1.push((function() {
              var _k, _len2, _results2;
              _results2 = [];
              for (_k = 0, _len2 = fields.length; _k < _len2; _k++) {
                field = fields[_k];
                _results2.push(fn(field));
              }
              return _results2;
            })());
          }
          return _results1;
        }
      };

      FormView.prototype.findGroup = function(name) {
        var g, group, _i, _len, _ref;
        _ref = this.groups;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          group = _ref[_i];
          if (group.options.name === name) {
            g = group;
          }
        }
        return g;
      };

      FormView.prototype.findField = function(name, group) {
        var fields;
        fields = [];
        this.eachField(group, function(field) {
          if (field.name === name) {
            return fields.push(field);
          }
        });
        return fields;
      };

      FormView.prototype.isValid = function() {
        return this.$$('form').valid();
      };

      FormView.prototype.getFormData = function() {
        var data;
        data = {};
        this.eachField((function(_this) {
          return function(field) {
            if (!field.submitThisField()) {
              return;
            }
            if (field.getFormData() === null) {
              return;
            }
            if (data[field.name] !== void 0) {
              if (!_.isArray(data[field.name])) {
                data[field.name] = [data[field.name]];
              }
              return data[field.name].push(field.getFormData());
            } else {
              return data[field.name] = field.getFormData();
            }
          };
        })(this));
        this.model.clear();
        this.model.set(data);
        return this.model.toJSON();
      };

      FormView.prototype.getFilters = function() {
        var filters;
        filters = [];
        this.eachField((function(_this) {
          return function(field) {
            var filter;
            filter = field.getFilter();
            if (filter) {
              return filters.push(filter);
            }
          };
        })(this));
        return filters;
      };

      FormView.prototype.setTabFormData = function(components) {
        var data;
        data = this.model.toJSON();
        return this.eachField(function(field) {
          return _.each(components, function(n, i) {
            if (n && n['__options__'].name === field.name) {
              if (_.has(data, field.name) || ' __ID__ __FORM_TYPE__ __FORM__FLAG__'.indexOf(field.name) > 0) {
                return field.loadFormData(data[field.name], data);
              }
            }
          });
        });
      };

      FormView.prototype.setFormData = function(data, onlyExists) {
        if (data == null) {
          data = {};
        }
        return this.eachField(function(field) {
          if (onlyExists === true) {
            if (_.has(data, field.name) || ' __ID__ __FORM_TYPE__ __FORM__FLAG__'.indexOf(field.name) > 0) {
              return field.loadFormData(data[field.name], data);
            }
          } else {
            return field.loadFormData(data[field.name], data);
          }
        });
      };

      FormView.prototype.reset = function() {
        return this.setFormData({});
      };

      FormView.prototype.fetchData = function(id) {
        this.model.clear();
        this.model.set('id', id);
        return this.model.fetch().done((function(_this) {
          return function() {
            return _this.setFormData(_this.model.toJSON());
          };
        })(this));
      };

      FormView.prototype.submit = function(options) {
        var deferred;
        deferred = $.Deferred();
        if (!this.isValid()) {
          deferred.reject();
        } else {
          this.getFormData();
          if (this.feature.extraFormData) {
            this.model.set(this.feature.extraFormData);
          }
          this.model.set(options);
          if (this.model.get('id') === '') {
            this.model.unset('id');
          }
          this.model.save().done(function(data) {
            return deferred.resolve(data);
          }).fail(function(data) {
            return deferred.reject();
          });
        }
        return deferred.promise();
      };

      FormView.prototype.getMaxColumns = function() {
        var group, i, _i, _len, _ref;
        i = 1;
        _ref = this.groups;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          group = _ref[_i];
          if (i < group.getColumns()) {
            i = group.getColumns();
          }
        }
        return i;
      };

      FormView.prototype.afterRender = function() {
        var deferred, promises;
        deferred = $.Deferred();
        promises = [];
        if (this.needExtraComponentRender === true) {
          promises.push(this.renderComponents());
        }
        this.eachField(function(field) {
          promises.push(field.afterRender());
          if (field.disabled) {
            if (' grid-picker tree-picker file-picker'.indexOf(field.type) > 0) {
              return $('#trigger-a-' + field.id, field.form.$el).unbind().css('cursor', 'not-allowed');
            } else {
              return field.form.$(field.id).attr('disabled', true);
            }
          }
        });
        $.when.apply($, promises).then((function(_this) {
          return function() {
            return $.when(_this.bindValidation()).then(function() {
              return deferred.resolve(this);
            });
          };
        })(this));
        return deferred.promise();
      };

      FormView.prototype.bindValidation = function() {
        var options, validator;
        if (!this.options.validation) {
          return;
        }
        options = this.options;
        return validator = this.$$('form').validate({
          rules: this.options.validation.rules,
          ignore: this.options.validation.ignore || '',
          onfocusout: function(el) {
            return validator.element(el);
          },
          errorPlacement: function(error, element) {
            var $el, elPos;
            $el = $(element);
            if (options.validation.errorsAppend) {
              elPos = $el.position();
              $(error).css({
                color: '#CC0000',
                position: 'absolute',
                top: elPos.top + $el.outerHeight()
              });
              return $(error).insertAfter(element);
            } else {
              if ($el.hasClass('tooltipstered')) {
                $el.tooltipster('destroy');
              }
              $(error).css({
                color: '#CC0000'
              });
              return $el.tooltipster({
                content: $(error),
                contentAsHTML: true,
                theme: 'tooltipster-shadow'
              });
            }
          },
          highlight: function(label) {
            return $(label).closest('.control-group').addClass('error');
          },
          success: function(label, element) {
            if (options.validation.errorsAppend) {
              $(label).closest('.control-group').removeClass('error');
              return $(label).remove();
            } else {
              $(element).tooltipster('destroy');
              $(element).closest('.control-group').removeClass('error');
              return $(element).attr('title', '');
            }
          }
        });
      };

      FormView.prototype.getTemplate = function() {
        var contents, group, groups, i, id, index, lis, o, oo, single, style, tab, unused, useableGroups, _i, _len, _ref;
        if (this.options.labelOnTop === false) {
          style = 'form-horizontal';
        }
        if (this.options.formName != null) {
          style += ' c-action-form c-action-form-' + this.options.formName;
        }
        o = {
          formClass: style,
          formName: this.options.formName
        };
        if (this.options.form.tabs) {
          unused = this.groups.slice(0);
          lis = [];
          contents = [];
          _ref = this.options.form.tabs;
          for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
            tab = _ref[i];
            id = tab.id;
            lis.push(this.getTabLiTemplate()({
              i: i,
              title: tab.title,
              id: id
            }));
            groups = tab.groups;
            groups = _.isArray(groups) ? groups : [groups];
            useableGroups = (function() {
              var _j, _len1, _ref1, _results;
              _results = [];
              for (_j = 0, _len1 = groups.length; _j < _len1; _j++) {
                group = groups[_j];
                if (!_.isEmpty((_ref1 = this.findGroup(group)) != null ? _ref1.fields : void 0)) {
                  _results.push(group);
                }
              }
              return _results;
            }).call(this);
            if (useableGroups.length === 1) {
              single = true;
            }
            contents.push(this.getTabContentTemplate()({
              content: ((function() {
                var _j, _len1, _results;
                _results = [];
                for (_j = 0, _len1 = groups.length; _j < _len1; _j++) {
                  group = groups[_j];
                  group = this.findGroup(group);
                  unused = _.without(unused, group);
                  _results.push(group.getTemplate(single));
                }
                return _results;
              }).call(this)).join(''),
              id: id,
              i: i
            }));
          }
          oo = {
            pinedGroups: ((function() {
              var _j, _len1, _results;
              _results = [];
              for (_j = 0, _len1 = unused.length; _j < _len1; _j++) {
                group = unused[_j];
                _results.push(group.getTemplate());
              }
              return _results;
            })()).join(''),
            lis: lis.join(''),
            content: contents.join('')
          };
          o.content = this.getTabLayoutTemplate()(oo);
        } else {
          useableGroups = (function() {
            var _j, _len1, _ref1, _results;
            _ref1 = this.groups;
            _results = [];
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              group = _ref1[_j];
              if (!_.isEmpty(group.fields)) {
                _results.push(group);
              }
            }
            return _results;
          }).call(this);
          if (useableGroups.length === 1) {
            single = true;
          }
          o.content = ((function() {
            var _j, _len1, _results;
            _results = [];
            for (index = _j = 0, _len1 = useableGroups.length; _j < _len1; index = ++_j) {
              group = useableGroups[index];
              _results.push(group.getTemplate(single, index));
            }
            return _results;
          })()).join('');
        }
        o.hiddens = ((function() {
          var _j, _len1, _ref1, _results;
          _ref1 = this.groups;
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            group = _ref1[_j];
            _results.push(group.getHiddenFieldsTemplate());
          }
          return _results;
        }).call(this)).join('');
        return _.template(this.getTemplateString())(o);
      };

      FormView.prototype.renderHtml = function(data) {
        return Handlebars.compile(this.getTemplate())(data);
      };

      FormView.prototype.getTemplateString = function() {
        return '<form class="<%= formClass %>" >\n    <%= content %>\n    <%= hiddens %>\n    <input type="hidden" name="__FORM_NAME__" value="<%= formName %>"/>\n</form>';
      };

      FormView.prototype.getTabLayoutTemplate = function() {
        return _.template('<%= pinedGroups %>\n<div>\n    <ul class="nav nav-tabs">\n        <%= lis %>\n    </ul>\n    <div class="tab-content">\n        <%= content %>\n    </div>\n</div>');
      };

      FormView.prototype.getTabLiTemplate = function() {
        return _.template('<li <% if (i == 0) {%>class="active" <%}%>><a data-target="<%= id %>" id="a-<%= id %>" data-toggle="tab"><%= title %></a></li>');
      };

      FormView.prototype.getTabContentTemplate = function() {
        return _.template('<div class="tab-pane <%if (i == 0) {%>active<%}%>" id="<%= id %>">\n    <%= content %>\n</div>');
      };

      return FormView;

    })(View);
    FormView.FormGroup = FormGroup;
    View.add('form-view', FormView);
    return FormView;
  });

}).call(this);
