// Generated by CoffeeScript 1.8.0
(function() {
  define(['handlebars', 'underscore'], function(H, _) {
    H.registerHelper('appearFalse', function(value) {
      if (value === false) {
        return 'false';
      } else {
        return value;
      }
    });
    H.registerHelper('perm', function(value, options) {
      var feature;
      if (!this['__view__']) {
        return options.fn(this);
      }
      feature = this['__view__'].feature;
      if (feature.isPermitted(value)) {
        return options.fn();
      } else {
        return options.inverse();
      }
    });
    H.registerHelper('auth', function(value, options) {
      var app, _ref, _ref1;
      if (!this['__view__']) {
        return options.fn(this);
      }
      app = this['__view__'].feature.module.getApplication();
      if ((_ref = app.settings) != null ? (_ref1 = _ref.session) != null ? _ref1.authenticated : void 0 : void 0) {
        return options.fn();
      } else {
        return options.inverse();
      }
    });
    H.registerHelper('user', function(value, options) {
      var app, _ref;
      if (!this['__view__']) {
        return options.fn(this);
      }
      app = this['__view__'].feature.module.getApplication();
      if ((_ref = app.settings) != null ? _ref.session : void 0) {
        return options.fn();
      } else {
        return options.inverse();
      }
    });
    H.registerHelper('view', function(value, options) {
      if (this['__viewName__'] === value && !this['__layout__']) {
        return options.fn(this);
      } else {
        return '';
      }
    });
    H.registerHelper('layout', function(value, options) {
      if (_.isFunction(value)) {
        if (this['__layout__'] === true) {
          return value(this);
        } else {
          return '';
        }
      } else {
        if (this['__layout__'] === true && this['__viewName__'] === value) {
          return options.fn(this);
        } else {
          return '';
        }
      }
    });
    return H;
  });

}).call(this);
