// Generated by CoffeeScript 1.8.0
(function() {
  define(['backbone', 'underscore', 'jquery'], function(Backbone, _, $) {
    var Sync;
    Sync = {
      online: function(method, model, options) {
        var beforeRequest, params, type;
        type = Sync.methodMap[method];
        params = {
          type: type,
          dataType: 'json',
          url: model.url(),
          contentType: 'application/x-www-form-urlencoded'
        };
        if (!options.data && model && (method === 'create' || method === 'update')) {
          params.data = _.extend(model.toJSON(), options.data || {});
          delete options.data;
        }
        params = _.extend(params, options);
        beforeRequest = options.beforeRequest || model.beforeRequest;
        if (_.isFunction(beforeRequest)) {
          beforeRequest(params, model, method);
        }
        return $.ajax(_.extend(params, options));
      },
      offline: function(method, model, options) {
        if (options == null) {
          options = {};
        }
      },
      storeForOffline: function(model) {},
      methodMap: {
        'create': 'POST',
        'update': 'PUT',
        'delete': 'DELETE',
        'read': 'GET'
      },
      fn: function(method, model, options) {
        var o;
        if (options == null) {
          options = {};
        }
        o = _.extend({}, options);
        if (window.navigator.onLine) {
          return Sync.online(method, model, o);
        } else {
          return Sync.offline(method, model, o);
        }
      }
    };
    Backbone.sync = Sync.fn;
    return Sync;
  });

}).call(this);
