// Generated by CoffeeScript 1.8.0
(function() {
  var __slice = [].slice;

  define({
    selectChanged: function() {
      var args, button, buttonView, el, feature, grid, id, view;
      feature = arguments[0], view = arguments[1], grid = arguments[2], args = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
      id = grid.getGridParam('selrow');
      buttonView = feature.formView.dialogFeature.views['dialog-buttons'];
      button = buttonView.buttons[0];
      el = buttonView.$(button.id);
      button.taskId = id;
      if (id) {
        return el.removeClass('disabled');
      } else {
        return el.addClass('disabled');
      }
    }
  });

}).call(this);
