// Generated by CoffeeScript 1.8.0
(function() {
  define(['cdeio/core/loader-plugin-manager', 'cdeio/scaffold/scaffold-feature-loader', 'cdeio/scaffold/form-view-loader', 'cdeio/scaffold/grid-view-loader', 'cdeio/scaffold/tree-view-loader', 'cdeio/scaffold/treetable-view-loader', 'cdeio/scaffold/process-view-loader', 'cdeio/scaffold/process-form-view-loader', 'cdeio/components/layout', 'cdeio/components/grid', 'cdeio/components/accordion', 'cdeio/components/tree', 'cdeio/components/select', 'cdeio/components/picker', 'cdeio/components/tabs', 'cdeio/components/datetimepicker', 'cdeio/features/tasks.feature/feature', 'cdeio/features/task-grid.feature/feature', 'cdeio/layouts/grid', 'cdeio/layouts/one-region'], function(LoaderPluginManager, scaffoldFeatureLoader, formViewLoader, gridViewLoader, treeViewLoader, treeTableViewLoader, processViewLoader, processFormViewLoader) {
    LoaderPluginManager.register(scaffoldFeatureLoader);
    LoaderPluginManager.register(formViewLoader);
    LoaderPluginManager.register(gridViewLoader);
    LoaderPluginManager.register(treeViewLoader);
    LoaderPluginManager.register(treeTableViewLoader);
    LoaderPluginManager.register(processViewLoader);
    return LoaderPluginManager.register(processFormViewLoader);
  });

}).call(this);
