// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cdeio/core/form/form-field', 'underscore', 'cdeio/components/masked-input'], function(FormField, _) {
    var MaskField;
    MaskField = (function(_super) {
      __extends(MaskField, _super);

      function MaskField() {
        MaskField.__super__.constructor.apply(this, arguments);
        this.type = 'text';
      }

      MaskField.prototype.getComponents = function() {
        if (this.readOnly) {
          return [];
        }
        return [
          _.extend({}, this.options, {
            type: 'mask',
            selector: this.id
          })
        ];
      };

      return MaskField;

    })(FormField);
    FormField.add('mask', MaskField);
    return MaskField;
  });

}).call(this);
