// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cdeio/core/form/form-field'], function(FormField) {
    var TextField;
    TextField = (function(_super) {
      __extends(TextField, _super);

      function TextField() {
        TextField.__super__.constructor.apply(this, arguments);
        this.type = 'text';
      }

      return TextField;

    })(FormField);
    FormField.add('text', TextField);
    return TextField;
  });

}).call(this);
