// Generated by CoffeeScript 1.8.0
(function() {
  define(function() {
    var sortable;
    sortable = {
      id: true,
      processInstanceId: true,
      processDefinitionId: true,
      startTime: true,
      endTime: true,
      durationInMillis: true,
      deleteReason: true,
      endActivityId: true,
      businessKey: true,
      startUserId: true,
      startActivityId: true,
      superProcessInstanceId: true
    };
    return {
      path: "completed",
      components: [
        function() {
          var c, o, _i, _len, _ref, _ref1;
          o = {
            type: "grid",
            selector: "grid",
            pager: "pager",
            columns: [
              {
                name: "id",
                header: "ID"
              }, {
                name: "name",
                header: "Name"
              }, {
                name: "startTime",
                header: "Start Time"
              }, {
                name: 'durationInMillis',
                header: 'Duration In Millis'
              }
            ]
          };
          if ((_ref = this.feature.startupOptions.option) != null ? _ref.finishedColumns : void 0) {
            o.columns = this.feature.startupOptions.option.finishedColumns;
          }
          _ref1 = o.columns;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            c = _ref1[_i];
            c.sortable = !!sortable[c.name];
          }
          return o;
        }
      ],
      avoidLoadingHandlers: true,
      avoidLoadingModel: true
    };
  });

}).call(this);
