// Generated by CoffeeScript 1.8.0
(function() {
  define(function() {
    var sortable;
    sortable = {
      id: true,
      name: true,
      description: true,
      priority: true,
      owner: true,
      assignee: true,
      processInstanceId: true,
      processDefinitionId: true,
      createTime: true,
      dueDate: true,
      startTime: true,
      endTime: true
    };
    return {
      components: [
        function() {
          var c, o, _i, _len, _ref, _ref1;
          o = {
            type: "grid",
            selector: "grid",
            multiple: true,
            columns: [
              {
                name: "id",
                header: "ID"
              }, {
                name: "name",
                header: "Name"
              }, {
                name: "createTime",
                header: "Create Time"
              }, {
                name: "assignee",
                header: "Assignee"
              }
            ]
          };
          if ((_ref = this.feature.startupOptions.option) != null ? _ref.toDoColumns : void 0) {
            o.columns = this.feature.startupOptions.option.toDoColumns;
          }
          _ref1 = o.columns;
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            c = _ref1[_i];
            c.sortable = !!sortable[c.name];
          }
          return o;
        }
      ],
      avoidLoadingHandlers: true
    };
  });

}).call(this);
